### ISSUE TITLE
middleware.Write does not have pointer receiver

### ISSUE THREAD

**Issue by lukechampine** [schollz/httpfileserver#1]
https://github.com/schollz/httpfileserver/blob/f352c00a7ad040f84a277855172c1a698410f453/httpfileserver.go#L68-L76

This method is setting the `numBytes` and `closed` fields, but the receiver is not a pointer.

**Comment by schollz** [comment]
You're right, thanks. I have to figure out how to change that since that Write function can't have a pointer.

**Comment by schollz** [comment]
Ok should be fixed now!

**Comment by lukechampine** [comment]
I don't understand your fix. Why can't you do:
```go
mware := &middleware{Writer: wc, ResponseWriter: w, maxBytes: fs.optionMaxBytesPerFile}
```
and give `Write` a pointer receiver?
